### ISSUE TITLE
First try

### ISSUE THREAD

**Issue by pjv** [dcramer/python-tools-tmbundle#1]
wow, if you could see the log of my google searches today... stuff like "textmate python", "textmate pyflakes pychecker", etc.

i cloned your repo into my bundles directory and this is what happened:
1. the bundle came in named "python-tools-tmbundle" instead of "python-tools.tmbundle" [just needed to replace the second hyphen with a dot]
2. the bundle doesn't seem to have defined the cmd-S command (at least for me). only the shft-cmd-V command.
3. when i invoke the shft-cmd-V command, this is the output i got:
   "/Users/paul/Library/Application Support/TextMate/Bundles/python-tools.tmbundle/Support/bin/pyflakes_html.py:19: syntax error, unexpected tIDENTIFIER, expecting $end"

hope this helps some. love the idea!

**Comment by dcramer** [comment]
Seems the editor wasnt saving as I expected, can you try the current ubild out now?

**Comment by pjv** [comment]
now i have both commands, but neither works. same output from the html output one, but the quick one gives me a half a monitor tooltip full of syntax errors in pyflakes_quick.py. i wonder if there is some kind of python path issue in my setup or something. i am currently running textmate via 'mate' in the context of a virtualenv. that said, the pyflakes support in the textmate python bundles seems to be working, though that is against pyflakes installed in the virtualenv and not one embedded in the bundle like you have.

**Comment by dcramer** [comment]
Ahh, had TM_RUBY instead of TM_PYTHON :)

**Comment by pjv** [comment]
that fixed the html based output and fixed the syntax errors in the tooltip (quick) output. but now i get no tooltip on cmd-S at all, even though i introduced a warning in the file that shows up in the html (cmd-shft-V) output.

**Comment by dcramer** [comment]
One more try. I think it's good now :)

**Comment by pjv** [comment]
yes. very nice. thanks for making it work. and for making it!
