### ISSUE TITLE
Small improvement to the readme

### ISSUE THREAD

**Issue by flegoff** [dcramer/python-tools-tmbundle#2]
Please remove dcramer@ from the following line :

   git clone https://dcramer@github.com/dcramer/python-tools-tmbundle.git ~/Library/Application\ Support/TextMate/Bundles/PythonTools.tmbundle

It will allow lazy users like me to copy/paste the line without having to enter your password when git will prompt for it ;-)

**Comment by dcramer** [comment]
Remove username from git clone line (closed by ee8812b937ab592a1c1d9c84a8a50b487c10e533)
